// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNjZGLCphusPHe-H3TvUofzArwbEYbWc0',
    appId: '1:151982891434:web:84a343bdc157cec65f0bd3',
    messagingSenderId: '151982891434',
    projectId: 'farm-app-2f36b',
    authDomain: 'farm-app-2f36b.firebaseapp.com',
    storageBucket: 'farm-app-2f36b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XVQhSE8uFBOiYCG9O4IKclUcLbqZTkM',
    appId: '1:151982891434:android:2951a614a05e04885f0bd3',
    messagingSenderId: '151982891434',
    projectId: 'farm-app-2f36b',
    storageBucket: 'farm-app-2f36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8dg6gihoq0gVDhtBNIX98vQUKKriYdQ',
    appId: '1:151982891434:ios:5e0f4ce514564cd15f0bd3',
    messagingSenderId: '151982891434',
    projectId: 'farm-app-2f36b',
    storageBucket: 'farm-app-2f36b.firebasestorage.app',
    iosBundleId: 'com.example.farmBuddyProjectIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn8dg6gihoq0gVDhtBNIX98vQUKKriYdQ',
    appId: '1:151982891434:ios:5e0f4ce514564cd15f0bd3',
    messagingSenderId: '151982891434',
    projectId: 'farm-app-2f36b',
    storageBucket: 'farm-app-2f36b.firebasestorage.app',
    iosBundleId: 'com.example.farmBuddyProjectIot',
  );
}
